#!/bin/bash

package_manager="dnf"
config="$HOME/.config/eww"
scripts_dir="$HOME/.local/bin"

dependencies=(
'gtk3-devel' 'pango' 'gdk-pixbuf2-devel' 'cairo-devel' 'glib2-devel'
'glibc-devel' 
)
for pkg in ${dependencies[@]}; do
    sudo dnf install $pkg
done

mkdir -p "$config/source"

git clone https://github.com/elkowar/eww "$config/source"

cd "$config/source"

cargo build --release --no-default-features --features x11

cd "target/release"

chmod +x ./eww

eww kill
if [[ ! -e "$HOME/.local/bin" ]]; then
    mkdir -p "$HOME/.local/bin"
fi
cp ./eww $scripts_dir/eww-copy

cd "$config"

rm -rf "$config/source"


