#!/bin/bash

config="$1"
if [[ ! -e $config ]]; then
    echo "invalid path"
    exit 1
fi

type_script="$HOME/.config/eww/common/scripts/connection_type"
declare -A type_icon=([full]="" [limited]="󰐻" [none]="")
update () {
    sleep 0.7
    state=$(nmcli networking connectivity check)
    eww -c $1 update connection_icon=${type_icon["$state"]}
}

update $config
nmcli device monitor | stdbuf -oL grep -E '^w.+(connected|disconnected|unavailable)$' \
    | stdbuf -oL awk -F ': ' '{print $2}' | while read -r _; do
    update $config
done

