#!/bin/bash

# themes=($(theme -l))
themes=("everforest" "dracula" "catppuccin" "gruvbox")
match=false
for theme in ${themes[@]}; do
    if [ "$theme" == "$1" ]; then
        match=true
        break
    fi
done
if [ "$match" == "false" ]; then
    echo "invalid theme: $1"
    exit 1
fi
config="$HOME/.config/i3"
colors="$config/colors"

cat "$colors/$1.conf" > "$colors/palette.conf"
cat "$colors/palette.conf" "$colors/i3-colors.conf" > "$config/colors.conf"
