#!/bin/bash

config="$HOME/.config/eww/bar"

eww -c $config open bar
eww -c $config update show_battery_percentage=false
eww -c $config update show_volume_percentage=false
bash "$HOME/.config/eww/common/scripts/start-daemons" --config="$config" --scripts=battery_*,mic_*,volume_*,connection_icon,bluetooth &
