#!/bin/bash

screenshots=~/Pictures/Screenshots
if [[ ! -e $screenshots ]]; then
    mkdir -p $screenshots
fi

CURRENT_DATE=$(date "+%Y-%m-%d_%H:%M:%S")
echo $CURRENT_DATE &> ~/tmp
maim --select "$screenshots/$CURRENT_DATE.png" &
# import -quality 90 ~/Pictures/Screenshots/$CURRENT_DATE.png &
