#!/bin/bash

logdir="$HOME/.config/i3/scripts/files"
log="$logdir/layout.log"
window="$HOME/.config/i3/scripts/keyboardw"
if [[ ! -e $logdir ]]; then
    mkdir $logdir
fi

if [[ ! -p "$log" ]]; then
    touch "$log"
fi

config="$HOME/.config/eww/keyboard"
bash "$window" 2>&1 > /dev/null &
layout=$(swaplayout fr,us,ar) 
# eww -c $config update selected=$layout
# eww -c "$HOME/.config/eww/bar" update layout=$layout
echo m >> $log
