#!/bin/bash
# dependencies: wpctl amixer bc sed awk

if [ "$1" == "mute" ]; then
    amixer set Master toggle
    exit
fi

max=150

percentage=$(wpctl get-volume @DEFAULT_SINK@ | sed 's/Volume: //g' | awk -F '[][]' '{print $1, $2}')

percentage=$(bc <<< "scale=0; $percentage * 100 / 1")

if [[ $percentage -ge $max && "$(echo $1 | grep -o '+')" == '+' ]]; then
    exit
fi

if ! amixer set Master $1 2> /dev/null; then
    echo invalid parameter $1
    exit 1
fi
