#!/bin/bash
# dependencies: wpctl pulseaudio-utils bc sed awk

mute=$(wpctl get-volume @DEFAULT_SINK@ | sed 's/Volume: //g' | awk -F '[][]' '{print $2}')

if [ "$1" == "mute" ]; then
    amixer set Master toggle 1> /dev/null
    exit
fi

if [ "$mute" == "MUTED" ]; then
    amixer set Master toggle > /dev/null
fi

if ! amixer set Master $1 1> /dev/null; then
    echo invalid parameter $1
    exit 1
fi
