-- require("flutter-tools").setup {
--   ui = {
--     notification_style = 'plugin'
--   },
--   decorations = {
--     statusline = {
--       app_version = true,
--       device = true,
--       project_config = true,
--     }
--   },
--   debugger = {
--     enabled = false,
--   },
--   flutter_lookup_cmd = "dirname $(which flutter)", -- example "dirname $(which flutter)" or "asdf where flutter"
--   root_patterns = { ".git", "pubspec.yaml" },
--   widget_guides = {
--     enabled = false,
--   },
--   closing_tags = {
--     highlight = "ErrorMsg", -- highlight for the closing tag
--     prefix = ">", -- character to use for close tag e.g. > Widget
--     priority = 10,
--     enabled = false -- set to false to disable
--   },
--   dev_log = {
--     enabled = true,
--     open_cmd = "15split", -- command to use to open the log buffer
--     focus_on_open = false, -- focus on the newly opened log window
--   },
--   dev_tools = {
--     autostart = false, -- autostart devtools server if not detected
--     auto_open_browser = false, -- Automatically opens devtools in the browser
--   },
--   outline = {
--     open_cmd = "30vnew", -- command to use to open the outline buffer
--     auto_open = false -- if true this will open the outline automatically when it is first populated
--   },
--   lsp = {
--     color = {
--       enabled = true, -- whether or not to highlight color variables at all, only supported on flutter >= 2.10
--       foreground = true, -- highlight the foreground
--       virtual_text = false, -- show the highlight using virtual text
--       virtual_text_str = "■", -- the virtual text character to highlight
--     },
--     --- OR you can specify a function to deactivate or change or control how the config is created
--     capabilities = function(config)
--       config.specificThingIDontWant = false
--       return config
--     end,
--     -- see the link below for details on each option:
--     -- https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md#client-workspace-configuration
--     settings = {
--       showTodos = true,
--       completeFunctionCalls = true,
--       analysisExcludedFolders = {"<path-to-flutter-sdk-packages>"},
--       renameFilesWithClasses = "prompt", -- "always"
--       enableSnippets = true,
--       updateImportsOnRename = true, -- Whether to update imports and other directives when files are renamed. Required for `FlutterRename` command.
--     }
--   }
-- }

-- lsp
require("lspconfig")["dartls"].setup({
    cmd = { vim.fn.expand("$HOME/development/flutter/bin/dart"), 'language-server', '--protocol=lsp' }
})
