sudo dnf install zathura
sudo dnf install texlive-scheme-medium
sudo dnf install 'tex(CormorantGaramond.sty)'
sudo dnf install 'tex(lastpage.sty)'
sudo dnf install 'tex(cfr-lm.sty)'
sudo dnf install 'tex(fullpage.sty)'
sudo dnf install 'tex(lingmacros.sty)'
sudo dnf install 'tex(lingmacros.cls)'
sudo dnf install 'tex(lingmacros)'
