#!/bin/bash

themesdir="$HOME/.config/nvim/lua/core/plugin_config/themes"

if [ "$1" == "" ]; then
    echo "please choose a theme, or use 'list' to view available themes"
    exit 1
fi

if [ "$1" == "list" ]; then
    ls $themesdir | awk -F'.' ' {print $1} '
    exit 1
fi

match=$(ls $themesdir | awk "/$1/ { print }")
if [[ "$match" == "" || "$match" != "$1.lua" ]]; then
    echo "invalid theme"
    exit 1
fi

# cp "$themesdir/$1.lua" "$HOME/.config/nvim/lua/core/plugin_config/theme.lua"
echo "require('core.plugin_config.themes.$1')" >  "$HOME/.config/nvim/lua/core/plugin_config/theme.lua"

