#!/usr/bin/env python3

from subprocess import check_output

icon_color = "#2A9D8F"
text_color = "#ffffff"

types = check_output("nmcli device show | awk '/GENERAL.TYPE/ {print $2}'", shell=True).decode("utf-8").split("\n")
names = check_output("nmcli device show | awk '/GENERAL.CONNECTION/ {print $2}'", shell=True).decode("utf-8").split("\n")
states = check_output("nmcli device show | awk -F'(' '/GENERAL.STATE/ {print $2}'", shell=True).decode("utf-8").split("\n")

text = ""
for i in range(0, len(types)):
    if ("connected" in states[i] and ")" in states[i]):
        if (types[i] == "wifi"):
            text = f"<span color='{icon_color}'> </span><span color='{text_color}'>{names[i]}</span>"
            break
        if (types[i] == "ethernet"):
            text = f"<span color='{icon_color}'>󰈀 </span><span color='{text_color}'>{names[i]}</span>"
            break

print(text)
