#!/bin/bash

pkg_managers=("apt" "dnf" "pacman" "emerge" "zypper" "brew")

for pkg_manager in ${pkg_managers[@]}; do
    if command -v $pkg_manager &> /dev/null; then
        echo $pkg_manager
        exit
    fi
done

echo unknown package manager

