#!/bin/bash

input=$(if [ "$1" == "" ]; then echo "fr,us,ar"; else echo "$1"; fi)
layouts=($(echo $input | awk 'BEGIN {RS=","} {print $0}'))
current=$(setxkbmap -query | grep layout | awk -F ':\\s+' '{print $2}')

setlayout () {
    index=$1
    current=${layouts[$(( (index + 1) % ${#layouts[@]} ))]} 
    setxkbmap $current
    echo $current

}

for i in $(seq 0 $(( ${#layouts[@]} - 1 ))); do
    if [ "${layouts[$i]}" == "$current" ]; then
        setlayout $i
        exit
    fi
    (( i++ ))
done

setlayout 0

