#!/bin/bash

input=$(if [ "$1" == "" ]; then echo "fr,us,ar,dv"; else echo "$1"; fi)
layouts=($(echo $input | awk 'BEGIN {RS=","} {print $0}'))
current=$(setxkbmap -query | grep layout | awk -F ':\\s+' '{print $2}')
if [[ "$current" == "dvorak" ]]; then
    current="dv"
fi

setlayout () {
    index=$1
    current=${layouts[$(( (index + 1) % ${#layouts[@]} ))]} 
    if [[ "$current" == "dv" ]]; then
        setxkbmap dvorak
    else
        setxkbmap $current
    fi
    echo $current

}

for i in $(seq 0 $(( ${#layouts[@]} - 1 ))); do
    if [ "${layouts[$i]}" == "$current" ]; then
        setlayout $i
        exit
    fi
    (( i++ ))
done

setlayout 3

