#!/bin/bash

change_theme() {
    wal -i "$1"
}

check() {
    if ! test -f "$1" && ! test -d "$1"; then
        echo $2
        exit 64
    fi
}

get_random_folder_element() {
    element=$(ls $1 | head -$(($RANDOM % $(ls $1 | wc -l) + 1)) | tail -1)
}

set_theme() {
    # rename the files that contain space and replace spaces with underscores
    rename " " "_" "$1"
    # update wallpaper
    wallpaper=$(echo $1| sed "s/ /_/g")

    change_theme $wallpaper
}

if [[ "$1" == "-r" ]] || [[ "$1" == "" ]]; then
    get_random_folder_element ~/Pictures/wallpapers
    theme="$HOME/Pictures/wallpapers/$element"
elif [ "$1" == "-l" ]; then
    ls ~/Pictures/wallpapers
    exit
else 
    theme="$HOME/Pictures/wallpapers/$1"
    check $theme "invalid theme $1"
fi
if [[ $2 == "" ]]; then
    get_random_folder_element $theme
    wallpaper="$theme/$element"
else
    wallpaper="$theme/$2"
    check $wallpaper "invalid file $2"
fi

set_theme $wallpaper 
