require("core.configs.editing.treesitter")
require("core.configs.editing.builtin")
require("core.configs.editing.lsp")
require("core.configs.editing.completion")
require("core.configs.editing.basic")
require("core.configs.editing.ufo")
require("core.configs.editing.refactoring")
require("core.configs.editing.vimtex")
